version: '3.8'

# networks:
#   monitor:
#     driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  # Expose local metrics 'OPTIONAL'
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    # networks:
    #   - monitor

  # Prometheus Server
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    ports:
      - 9090:9090
    extra_hosts:
      - "crowdsec:${REMOTE_NODEEXPORTER_IP:-host-gateway}"
    
    # networks:
    #   - monitor

  # Grafana Latest with provisioning (Dashboards + datasources)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-password}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
    # networks:
    #   - monitor
    ports:
      - 3000:3000

    labels:
      org.label-schema.group: "monitoring"
    extra_hosts:
      - "prometheus:${REMOTE_PROMETHEUS_IP:-host-gateway}"

  pushgateway:
    image: prom/pushgateway:v1.2.0
    container_name: pushgateway
    restart: unless-stopped
    expose:
      - 9091
    # networks:
    #   - monitor
    labels:
      org.label-schema.group: "monitoring"

# TODO Check for usage

  # alertmanager:
  #   image: prom/alertmanager:v0.20.0
  #   container_name: alertmanager
  #   volumes:
  #     - ./alertmanager/config:/etc/alertmanager
  #   command:
  #     - '--config.file=/etc/alertmanager/config.yml'
  #     - '--storage.path=/alertmanager'
  #   restart: unless-stopped
  #   expose:
  #     - 9093
  #   # networks:
  #   #   - monitor
  #   labels:
  #     org.label-schema.group: "monitoring"

# Docker Monitoring

  cadvisor:
    image: gcr.io/google-containers/cadvisor:v0.34.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      #- /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
    restart: unless-stopped
    expose:
      - 8080
    labels:
      org.label-schema.group: "monitoring"